[general]
live_config_reload = true

[cursor]
blink_interval = 500
thickness = 0.10
unfocused_hollow = true

[cursor.style]
shape = "Beam"
blinking = "On"

[font]
size = 14.0

[font.normal]
# family = "Adwaita Mono"
family = "Lilex Nerd Font"
# style = "Regular"
# style = "Light"

[scrolling]
multiplier = 1

[selection]
save_to_clipboard = true

[terminal.shell]
program = "bash"
#program = "fish"
#program = "zsh"
#program = "pwsh"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 1.00
startup_mode = "Maximized"
title = "alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"

[window.padding]
x = 10
y = 10

#######################################################################################################################
# KEYBOARD
#######################################################################################################################
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

#######################################################################################################################
# MOUSE
#######################################################################################################################
[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

#######################################################################################################################
# COLORS - dracula scheme
#######################################################################################################################
# [colors.primary]
# background = "#282a36"
# foreground = "#f8f8f2"
# bright_foreground = "#ffffff"

# [colors.cursor]
# text = "#282a36"
# cursor = "#f8f8f2"

# [colors.vi_mode_cursor]
# text = "CellBackground"
# cursor = "CellForeground"

# [colors.selection]
# text = "CellForeground"
# background = "#44475a"

# [colors.normal]
# black = "#21222c"
# red = "#ff5555"
# green = "#50fa7b"
# yellow = "#f1fa8c"
# blue = "#bd93f9"
# magenta = "#ff79c6"
# cyan = "#8be9fd"
# white = "#f8f8f2"

# [colors.bright]
# black = "#6272a4"
# red = "#ff6e6e"
# green = "#69ff94"
# yellow = "#ffffa5"
# blue = "#d6acff"
# magenta = "#ff92df"
# cyan = "#a4ffff"
# white = "#ffffff"

# [colors.search.matches]
# foreground = "#44475a"
# background = "#50fa7b"

# [colors.search.focused_match]
# foreground = "#44475a"
# background = "#ffb86c"

# [colors.footer_bar]
# background = "#282a36"
# foreground = "#f8f8f2"

# [colors.hints.start]
# foreground = "#282a36"
# background = "#f1fa8c"

# [colors.hints.end]
# foreground = "#f1fa8c"
# background = "#282a36"
